// GENERATED by scripts/gen-asset-registry.py from assets/manifest.json.
// Do not edit: re-run the script. scripts/check-assets.py fails CI when this
// file and the manifest disagree.
//
// Why a generated file: Metro bundles an image only through a static
// `require('<literal path>')`, so the manifest cannot be resolved at runtime.
// Everything here is a projection of the manifest — the manifest stays the
// authority (domain_spec/imagery-and-iconography, "The source of truth is the
// manifest, not this document").

import type { ImageSource } from 'expo-image';

/** Mirrors the manifest's `status` field. Only `confirmed` — a human has seen
 *  this picture beside this dish — may reach a surface. */
export type AssetStatus = 'confirmed' | 'candidate' | 'unmapped';

export interface RegisteredAsset {
  /** The manifest entry's `key`, so a resolution can be named in a report. */
  key: string;
  /** The bundled module, as Metro's `require` returns it — a number on native,
   *  a `{ uri, width, height }` object on web — for a `confirmed` entry only.
   *  Anything else is `null`: not bundled, because it may not be shown. */
  source: ImageSource | number | null;
  status: AssetStatus;
  /** The manifest's `alt_de`. German is the working language. */
  altDe: string;
}

/** Dish illustrations, keyed by menu item id. */
export const DISH_ILLUSTRATIONS: Readonly<Record<string, RegisteredAsset>> = {
  '1-pizza-margherita': {
    key: 'menu/pizza/1-pizza-margherita',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Margherita mit Oregano',
  },
  '2-pizza-cipolla': {
    key: 'menu/pizza/2-pizza-cipolla',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Cipolla mit Zwiebeln',
  },
  '3-pizza-napoli': {
    key: 'menu/pizza/3-pizza-napoli',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Napoli mit Oliven, Sardellen, Knoblauch',
  },
  '4-pizza-diavolo': {
    key: 'menu/pizza/4-pizza-diavolo',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Diavolo mit Paprika, Tabasco',
  },
  '5-pizza-salami': {
    key: 'menu/pizza/5-pizza-salami',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Salami mit Salami',
  },
  '6-pizza-quattro-formaggi': {
    key: 'menu/pizza/6-pizza-quattro-formaggi',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Quattro Formaggi mit 4 verschiedene Käsesorten',
  },
  '7-pizza-prosciutto': {
    key: 'menu/pizza/7-pizza-prosciutto',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Prosciutto mit Pizzabelag-Vorderschinken',
  },
  '8-pizza-funghi': {
    key: 'menu/pizza/8-pizza-funghi',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Funghi mit Champignons',
  },
  '9-pizza-toscana': {
    key: 'menu/pizza/9-pizza-toscana',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Toscana mit Pizzabelag-Vorderschinken, Ananas',
  },
  '10-pizza-hawaii': {
    key: 'menu/pizza/10-pizza-hawaii',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Hawaii mit Pizzabelag-Vorderschinken, Ananas',
  },
  '11-pizza-marinara': {
    key: 'menu/pizza/11-pizza-marinara',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Marinara mit Thunfisch, Zwiebeln',
  },
  '12-pizza-mimmo': {
    key: 'menu/pizza/12-pizza-mimmo',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Mimmo mit Pizzabelag-Vorderschinken, Thunfisch',
  },
  '13-calzone': {
    key: 'menu/pizza/13-calzone',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Calzone mit Salami, Zwiebeln, Pizzabelag-Vorderschinken, Champignons',
  },
  '14-pizza-don-camillo': {
    key: 'menu/pizza/14-pizza-don-camillo',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Don Camillo mit Pizzabelag-Vorderschinken, Spinat, Oliven, Knoblauch, Peperoni',
  },
  '15-pizza-quattro-stagioni': {
    key: 'menu/pizza/15-pizza-quattro-stagioni',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Quattro Stagioni mit Pizzabelag-Vorderschinken, Champignons, Paprika, Thunfisch, Oliven',
  },
  '16-pizza-capricciosa': {
    key: 'menu/pizza/16-pizza-capricciosa',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Capricciosa mit Pizzabelag-Vorderschinken, Salami, Champignons, Krabben',
  },
  '17-pizza-ozeano': {
    key: 'menu/pizza/17-pizza-ozeano',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Ozeano mit Meeresfrüchte, Thunfisch, Sardellen, Knoblauch',
  },
  '18-pizza-mamma-mia': {
    key: 'menu/pizza/18-pizza-mamma-mia',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Mamma Mia mit Spinat, Krabben, Knoblauch',
  },
  '19-pizza-gamberetti': {
    key: 'menu/pizza/19-pizza-gamberetti',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Gamberetti mit Krabben, Knoblauch',
  },
  '20-pizza-pepone': {
    key: 'menu/pizza/20-pizza-pepone',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Pepone mit Pizzabelag-Vorderschinken, Thunfisch, Krabben, Knoblauch',
  },
  '21-pizza-sandro-s-spezial': {
    key: 'menu/pizza/21-pizza-sandro-s-spezial',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Sandro`s Spezial mit Salami, Sauce Hollandaise, Jalapenos',
  },
  '22-pizza-romino-s': {
    key: 'menu/pizza/22-pizza-romino-s',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Romino´s mit Broccoli, Spinat, Schafskäse',
  },
  '23-pizza-siciliano': {
    key: 'menu/pizza/23-pizza-siciliano',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Siciliano mit Tomaten, Mozzarella, Oliven',
  },
  '24-pizza-venezia': {
    key: 'menu/pizza/24-pizza-venezia',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Venezia mit Spinat, Champignons, Zwiebeln, Knoblauch',
  },
  '25-pizza-firenze': {
    key: 'menu/pizza/25-pizza-firenze',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Firenze mit Paprika, Zwiebeln, Artischocken, Knoblauch',
  },
  '26-pizza-spaghetti': {
    key: 'menu/pizza/26-pizza-spaghetti',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Spaghetti mit mit Spaghetti Bolognese',
  },
  '27-pizza-de-pollo': {
    key: 'menu/pizza/27-pizza-de-pollo',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza de Pollo mit Hähnchenfleischstreifen, Cherrytomaten, Broccoli, Zwiebeln, Sauce Hollandaise',
  },
  '28-pizza-portofino': {
    key: 'menu/pizza/28-pizza-portofino',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza Portofino mit Lachs, Mozzarella, Spinat, Knoblauch',
  },
  '29-pizza-de-parma': {
    key: 'menu/pizza/29-pizza-de-parma',
    source: null,
    status: 'candidate',
    altDe: 'Illustration: Pizza de Parma mit Parmaschinken, Rucola, Parmesan',
  },
};

/** Category icons, keyed by category id. */
export const CATEGORY_ICONS: Readonly<Record<string, RegisteredAsset>> = {
  'pizza': {
    key: 'icons/category/pizza',
    source: null,
    status: 'candidate',
    altDe: 'Pizza',
  },
  'vorspeisen': {
    key: 'icons/category/vorspeisen',
    source: null,
    status: 'candidate',
    altDe: 'Vorspeisen',
  },
  'antipasti-misto': {
    key: 'icons/category/antipasti-misto',
    source: null,
    status: 'candidate',
    altDe: 'Antipasti Misto',
  },
  'nudeln': {
    key: 'icons/category/nudeln',
    source: null,
    status: 'candidate',
    altDe: 'Nudeln',
  },
  'frisch-aus-dem-ofen': {
    key: 'icons/category/frisch-aus-dem-ofen',
    source: null,
    status: 'candidate',
    altDe: 'Frisch aus dem Ofen',
  },
  'mexikanisch': {
    key: 'icons/category/mexikanisch',
    source: null,
    status: 'candidate',
    altDe: 'Mexikanisch',
  },
  'salate': {
    key: 'icons/category/salate',
    source: null,
    status: 'candidate',
    altDe: 'Salate',
  },
  'vegetarische-auflaeufe': {
    key: 'icons/category/vegetarische-auflaeufe',
    source: null,
    status: 'candidate',
    altDe: 'Vegetarische Aufläufe',
  },
  'fisch': {
    key: 'icons/category/fisch',
    source: null,
    status: 'candidate',
    altDe: 'Fisch',
  },
  'schweinefilet': {
    key: 'icons/category/schweinefilet',
    source: null,
    status: 'candidate',
    altDe: 'Schweinefilet',
  },
  'schnitzel': {
    key: 'icons/category/schnitzel',
    source: null,
    status: 'candidate',
    altDe: 'Schnitzel',
  },
  'getraenke': {
    key: 'icons/category/getraenke',
    source: null,
    status: 'candidate',
    altDe: 'Getränke',
  },
  'angebote': {
    key: 'icons/category/angebote',
    source: null,
    status: 'candidate',
    altDe: 'Angebote',
  },
};
