#!/usr/bin/env python3
"""Project `assets/manifest.json` into a TypeScript module the app can bundle.

Metro resolves image assets only through a static `require('<literal path>')`,
so the manifest cannot be walked at runtime to find a file — every bundled
picture needs its own `require` written out in source. Writing 42 of those by
hand, beside a manifest that already names every file, is how the two drift.
This script writes them from the manifest instead, and `scripts/check-assets.py`
fails CI when the written module and the manifest disagree.

What it carries across, per entry: the menu-item or category id it joins on
(`maps_to`), the manifest `key`, the `status` and the German alt text — and a
`require()` of the file ONLY for a `confirmed` entry. A `candidate` binding may
not reach a surface (`policy/ux-priorities`, clause
`an-image-beside-a-price-is-a-claim`), so its bytes are not bundled either: the
app never ships a picture it is forbidden to show. Promoting an entry in the
manifest and re-running this script is what puts the file in the bundle; the
resolver in `src/lib/dish-art.ts` reads the status again on the way out.

Stdlib only, like its sibling. Usage:

    python scripts/gen-asset-registry.py           # write src/lib/asset-registry.generated.ts
    python scripts/gen-asset-registry.py --check   # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MOBILE = Path(__file__).resolve().parent.parent
MANIFEST = MOBILE / "assets" / "manifest.json"
OUTPUT = MOBILE / "src" / "lib" / "asset-registry.generated.ts"

HEADER = """\
// GENERATED by scripts/gen-asset-registry.py from assets/manifest.json.
// Do not edit: re-run the script. scripts/check-assets.py fails CI when this
// file and the manifest disagree.
//
// Why a generated file: Metro bundles an image only through a static
// `require('<literal path>')`, so the manifest cannot be resolved at runtime.
// Everything here is a projection of the manifest — the manifest stays the
// authority (domain_spec/imagery-and-iconography, "The source of truth is the
// manifest, not this document").

import type { ImageSource } from 'expo-image';

/** Mirrors the manifest's `status` field. Only `confirmed` — a human has seen
 *  this picture beside this dish — may reach a surface. */
export type AssetStatus = 'confirmed' | 'candidate' | 'unmapped';

export interface RegisteredAsset {
  /** The manifest entry's `key`, so a resolution can be named in a report. */
  key: string;
  /** The bundled module, as Metro's `require` returns it — a number on native,
   *  a `{ uri, width, height }` object on web — for a `confirmed` entry only.
   *  Anything else is `null`: not bundled, because it may not be shown. */
  source: ImageSource | number | null;
  status: AssetStatus;
  /** The manifest's `alt_de`. German is the working language. */
  altDe: string;
}
"""


def ts_string(value: str) -> str:
    """A single-quoted TS string literal, matching the rest of `src/`."""
    escaped = (value.replace("\\", "\\\\").replace("'", "\\'")
               .replace("\n", "\\n").replace("\r", "\\r"))
    return f"'{escaped}'"


def comment_text(value: str) -> str:
    """Text safe inside a `/** … */` comment: a `*/` in it may not close it."""
    return value.replace("*/", "* /")


def render_table(name: str, doc: str, entries: list[dict]) -> str:
    """One `Record<id, RegisteredAsset>` keyed by what the entry `maps_to`."""
    rows: list[str] = []
    seen: dict[str, str] = {}
    for e in entries:
        key = e.get("key")
        status = e.get("status")
        if status not in ("confirmed", "candidate", "unmapped"):
            raise SystemExit(f"{key}: invalid status {status!r}")
        targets = list(e.get("maps_to", []))
        if status == "unmapped" and targets:
            raise SystemExit(f"{key}: status 'unmapped' but maps_to {targets!r} — "
                             f"an entry is bound or unmapped, not both")
        rel = e.get("file")
        if not rel:
            raise SystemExit(f"{key}: no file")
        if not rel.startswith("assets/"):
            raise SystemExit(f"{key}: file {rel!r} is outside assets/")
        module = "@/" + rel
        for target in targets:
            if target in seen:
                raise SystemExit(
                    f"{target!r} is mapped by both {seen[target]} and {e['key']}; "
                    f"one id resolves to one picture")
            seen[target] = e["key"]
            # Only a confirmed entry gets a require(): that is what puts the
            # file in the bundle, and a picture that may not be shown is not
            # shipped.
            source = f"require({ts_string(module)})" if status == "confirmed" else "null"
            rows.append(
                f"  {ts_string(target)}: {{\n"
                f"    key: {ts_string(e['key'])},\n"
                f"    source: {source},\n"
                f"    status: {ts_string(status)},\n"
                f"    altDe: {ts_string(e.get('alt_de', ''))},\n"
                f"  }},"
            )
    body = "\n".join(rows)
    return (
        f"\n/** {comment_text(doc)} */\n"
        f"export const {name}: Readonly<Record<string, RegisteredAsset>> = {{\n"
        f"{body}\n"
        f"}};\n"
    )


def render(manifest: dict) -> str:
    join = manifest.get("join_keys", {})
    images = render_table(
        "DISH_ILLUSTRATIONS",
        f"Dish illustrations, keyed by {join.get('images', 'menu item id')}.",
        list(manifest.get("images", [])),
    )
    icons = render_table(
        "CATEGORY_ICONS",
        f"Category icons, keyed by {join.get('icons', 'category id')}.",
        list(manifest.get("icons", [])),
    )
    return HEADER + images + icons


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare against the committed file instead of writing it")
    args = ap.parse_args()

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    want = render(manifest)

    if args.check:
        have = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if have != want:
            print(f"STALE: {OUTPUT.relative_to(MOBILE).as_posix()} does not match "
                  f"assets/manifest.json — re-run scripts/gen-asset-registry.py",
                  file=sys.stderr)
            return 1
        print(f"registry          : {OUTPUT.relative_to(MOBILE).as_posix()} matches the manifest")
        return 0

    OUTPUT.write_text(want, encoding="utf-8", newline="\n")
    entries = list(manifest.get("images", [])) + list(manifest.get("icons", []))
    bundled = sum(1 for e in entries if e.get("status") == "confirmed")
    print(f"wrote {OUTPUT.relative_to(MOBILE).as_posix()}: "
          f"{len(manifest.get('images', []))} illustrations, "
          f"{len(manifest.get('icons', []))} icons, "
          f"{bundled} confirmed and therefore bundled")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
